name: Mostrar fecha
on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches-ignore:
      - main
  
jobs:
  print-date:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir fecha actual
        run: date