name: expresions
on: workflow_dispatch
jobs:
  test-expressions:
    runs-on: ubuntu-latest
    #se ejecuta una vez por cada combinacion del matrix
    strategy:
      matrix:
        name: 
          - alice
          - bob
          - carol
        color: [ red, green, blue ]
    steps:
    # se evalua antes de enviar al servidor
      - run: echo ${{ github.actor }}
      - run: echo "Hello, ${{ matrix.name }}! Your favorite color is ${{ matrix.color }}."